### ISSUE TITLE
Тестовый контур

### ISSUE THREAD

**Issue by aliczin** [zhichkin/dajet-metadata#1]
предлагаю рассмотреть следующий вариант

* docker up mssql
* load db from sql 
* dotnet test

**Comment by zhichkin** [comment]
Какие артефакты нужно создать, чтобы всё вышеописанное заработало ? Я не силён в docker, но идея мне нравится.

**Comment by zhichkin** [comment]
В ближайшее время делать не планирую. Можно обсудить это на моём канале в Телеграмм https://t.me/dajet_studio
