### ISSUE TITLE
Nuget пакета для варианта сборки под OScript 

### ISSUE THREAD

**Issue by aliczin** [zhichkin/dajet-metadata#2]
попробуйте опубликовать NuGet пакет - тогда можно будет создать класс обертку для OScript

https://github.com/dmpas/oscript-component-example

**Comment by zhichkin** [comment]
Интеграцию с OScript не планирую.

**Comment by zhichkin** [comment]
[NuGet пакет DaJet.Metadata](https://www.nuget.org/packages/DaJet.Metadata/)
