### ISSUE TITLE
При чтении конфигураций в режимах совместимости 8.1 и 8.2 не совсем верно определяется свойство "Version"

### ISSUE THREAD

**Issue by ZlobinDV** [zhichkin/dajet-metadata#3]
Пример:

Name = УправлениеПроизводственнымПредприятием
Alias = Управление производственным предприятием, редакция 1.3
Comment =
Version = 000,2
ConfigVersion = 1.3.62.1
SyncCallsMode = Use
DataLockingMode = Managed
ModalWindowMode = Use
AutoNumberingMode = DoNotFreeAutomatically
UICompatibilityMode = Taxi

Не понятно, как сопоставить Version = 000,2 что это режим совместимости 8.2.13.

**Comment by zhichkin** [comment]
Ошибка исправлена в версии [v0.2](https://github.com/zhichkin/dajet-metadata/releases/tag/v0.2)
