### ISSUE TITLE
Возможно ли сделать вывод в формате JSON

### ISSUE THREAD

**Issue by demonisius** [zhichkin/dajet-metadata#4]
Было бы очень удобно для совместимости с Zabbix

**Comment by zhichkin** [comment]
Метаданные 1С в JSON ? Есть типовая выгрузка схемы метаданных из 1С в XML. Зачем в Zabbix ?
Уточните, пожалуйста, сценарий использования.

**Comment by demonisius** [comment]
Прошу прощения за не совсем корректную формулировку. Имелся ввиду вывод утилиты dajet в консоль.
В принципе вопрос решился добавлением кода в Ваш код (ключа запуска и вывода тех же данных, только в виде JSON и кодировке UTF8. Собственно, это понадобилось для создания экрана в Zabbix с сводной таблицей всех 1С баз на сервере MSSQL с указанием названия конфигурации и ее версии.
